# Generated by Django 4.2.7 on 2025-10-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='examcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
