# Generated by Django 4.2.7 on 2025-10-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0003_userprofile_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('prelims', 'Preliminary Exam'), ('mains', 'Mains Exam'), ('both', 'Both Prelims & Mains')], default='prelims', max_length=20)),
                ('answer_key_file', models.FileField(blank=True, null=True, upload_to='answer_keys/')),
                ('answer_key_link', models.URLField(blank=True)),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examportal.upcomingexam')),
            ],
        ),
    ]
