# Generated by Django 4.2.7 on 2025-10-28 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examportal', '0004_answerkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('notes_covered', models.ManyToManyField(blank=True, to='examportal.note')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examportal.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_notes', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed_notes', models.ManyToManyField(blank=True, to='examportal.note')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examportal.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('daily_study_goal', models.IntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examportal.upcomingexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
