# Generated by Django 5.1.7 on 2025-10-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0005_userstudysession_userprogress_examtarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='examtarget',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
    ]
