# Generated by Django 5.1.7 on 2025-10-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0006_alter_admitcard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingexam',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
    ]
