# Generated by Django 4.2.7 on 2025-10-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0008_alter_admitcard_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingexam',
            name='application_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='eligibility_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='exam_pattern',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='official_notification',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='syllabus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='vacancy_details',
            field=models.TextField(blank=True),
        ),
    ]
