# Generated by Django 4.2.7 on 2025-10-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0009_upcomingexam_application_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingexam',
            name='date_extend_notice',
            field=models.URLField(blank=True, help_text='Date Extend Notice Link'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='information_bulletin',
            field=models.URLField(blank=True, help_text='Download Information Bulletin'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='official_website',
            field=models.URLField(blank=True, help_text='Official Website Link'),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='application_fee',
            field=models.CharField(blank=True, help_text='General/OBC/SC/ST fees', max_length=200),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='apply_link',
            field=models.URLField(blank=True, help_text='Apply Online Link'),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Educational qualification, age limit, etc.'),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='exam_pattern',
            field=models.TextField(blank=True, help_text='Exam stages, marks distribution, etc.'),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='official_notification',
            field=models.URLField(blank=True, help_text='Official Notification PDF'),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Topics and subjects covered'),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='vacancy_details',
            field=models.TextField(blank=True, help_text='Number of posts, categories, etc.'),
        ),
    ]
