# Generated by Django 5.1.7 on 2025-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0010_upcomingexam_date_extend_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingexam',
            name='age_max',
            field=models.IntegerField(default=30, help_text='Maximum age requirement'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='age_min',
            field=models.IntegerField(default=18, help_text='Minimum age requirement'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='age_relaxation_details',
            field=models.TextField(blank=True, help_text='Age relaxation rules'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='correction_dates',
            field=models.CharField(blank=True, help_text='Correction window dates', max_length=200),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='educational_qualification',
            field=models.TextField(blank=True, help_text='Required educational qualifications'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='fee_female',
            field=models.CharField(blank=True, help_text='Fee for Female candidates', max_length=200),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='fee_general',
            field=models.CharField(blank=True, help_text='Fee for General category', max_length=200),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='fee_obc',
            field=models.CharField(blank=True, help_text='Fee for OBC category', max_length=200),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='fee_payment_last_date',
            field=models.DateField(blank=True, help_text='Last date for fee payment', null=True),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='fee_refund_policy',
            field=models.TextField(blank=True, help_text='Fee refund policy details'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='fee_sc_st',
            field=models.CharField(blank=True, help_text='Fee for SC/ST category', max_length=200),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='how_to_apply',
            field=models.TextField(blank=True, help_text='Step-by-step application process'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='payment_modes',
            field=models.TextField(blank=True, help_text='Accepted payment modes'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='percentage_required',
            field=models.TextField(blank=True, help_text='Percentage requirements for different categories'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='total_vacancies',
            field=models.IntegerField(default=0, help_text='Total number of vacancies'),
        ),
        migrations.AddField(
            model_name='upcomingexam',
            name='vacancy_breakdown',
            field=models.TextField(blank=True, help_text='JSON or formatted text for category-wise vacancies'),
        ),
        migrations.AlterField(
            model_name='examtarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
