# Generated by Django 5.1.7 on 2025-11-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0011_upcomingexam_age_max_upcomingexam_age_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingexam',
            name='age_max',
            field=models.IntegerField(blank=True, help_text='Maximum age requirement', null=True),
        ),
        migrations.AlterField(
            model_name='upcomingexam',
            name='age_min',
            field=models.IntegerField(blank=True, help_text='Minimum age requirement', null=True),
        ),
    ]
